### ISSUE TITLE
Dot import does not work

### ISSUE THREAD

**Issue by nyxkrage** [oxfeeefeee/goscript#10]
The Dot import syntax brings the entire package into the current namespace. So, you don’t have to call the functions using the package name. You can directly call them.
## Reproduction code
```go
package main

import (
  . "fmt2"
)

func main() {
  Println("Hello, World!")
}
```

## Expected Results
That it would print out "Hello, World!"

## Actual Results
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ...goscript/codegen/src/package.rs:47:60
```

**Comment by oxfeeefeee** [comment]
Fixed: https://github.com/oxfeeefeee/goscript/commit/53df963c99bf6e4893f882525820aa667e56b714

Thanks for helping!
