### ISSUE TITLE
Type conversion issue

### ISSUE THREAD

**Issue by darmie** [oxfeeefeee/goscript#16]
I am working from the `register-based` library, because that is where I have managed to use the FFI API extensively. But I am having a type conversion problem

I have this go script file
```go
package main

import (
	"zflow"
	"fmt2"
)

var in = zflow.Inputs()  // this returns map[string]interface{} type

func main() {
	fmt2.Println(in) // this prints map[left:1 right:2]
	// get inputs
	data, ok := in.(map[string]interface{})
	fmt2.Println(ok) // this prints false
	fmt2.Println(data) // this prints <nil(map)>
	
	left := data["left"]
	fmt2.Println(left) // this prints <nil>
  
}
```
Output:
```go
map[right:2 left:1]
false
<nil(map)>
<nil>
```

Expected output
https://go.dev/play/p/qPNzh1RmyiQ
```go
map[left:1 right:2]
true
map[left:1 right:2]
2
```

How do I correctly read a map value that is sent into the runtime via FFI function call?

**Comment by oxfeeefeee** [comment]
I reproduced this bug, will fix.
Thanks for reporting.

**Comment by oxfeeefeee** [comment]
Get the fix from the latest source or wait for the next release.
