### ISSUE TITLE
Type assertion fails

### ISSUE THREAD

**Issue by darmie** [oxfeeefeee/goscript#19]
Unwrapping `b.as_ref()` is not guaranteed, and fails sometimes when you pass an interface{} value into an ffi function. 

https://github.com/oxfeeefeee/goscript/blob/04d1cb08fabd1a28b4993aa314e3354184992885/vm/src/vm.rs#L1843

I wonder what the general behavior would be if you applied this as a fix

```rs
let want_meta = want_meta.as_metadata();
if b.is_none() {
   return Ok((want_meta.zero(metas, gcc), false));
}
let meta = b.as_ref().unwrap().0;
```

**Comment by oxfeeefeee** [comment]
Made a few changes, see the CL above

**Comment by darmie** [comment]
So I am sending data from FFI function to the runtime as an interface, this data could be any underlying type. The test scenario I worked with sends a `map[string]interface{}` which will be received as an `interface{}` type in Goscript code, it gets trickier by the time I try to access the map's elements , that was when I started getting the type assertion errors.

Based on your comment in the commit above:
> if you pass `None` to clone_mb_from, the returned interface won't behave like
> a normal interface. you cannot cast it or call it's methods. 

How do I know what to pass into clone_mb_from ?

**Comment by oxfeeefeee** [comment]
I realized the previous API requires too much understanding of the inner workings, I changed it so that you need to pass the metas of the interface and the value. Which are still hard to use, will figure out some improments.
For now, for your case, you can get the interface meta via PrimitiveMeta.empty_iface, and Meta::new_map() for the value.

**Comment by oxfeeefeee** [comment]
> So I am sending data from FFI function to the runtime as an interface, this data could be any underlying type. The test scenario I worked with sends a `map[string]interface{}` which will be received as an `interface{}` type in Goscript code, it gets trickier by the time I try to access the map's elements , that was when I started getting the type assertion errors.
> 
> Based on your comment in the commit above:
> 
> > if you pass `None` to clone_mb_from, the returned interface won't behave like
> > a normal interface. you cannot cast it or call it's methods.
> 
> Consider this code:
> 
> ```go
> package main
> 
> import "my_ffi"
> 
> func main() {
> 	var in = my_ffi.GetData()
> 	// get inputs
> 	data, ok := in.(map[string]interface{})
> 	assert(ok)
> 
> 	left, _ := data["left"].(int) // <<== Type assertion error starts here
> 	right, _ := data["right"].(int)
> }
> ```
> 
> How do I know what to pass into `clone_mb_from` ?
> 
> This is how I convert `serde_json::Value` types to `GosValue`
> 
> ```rust
> fn to_go_value(ctx: &FfiCtx, value: Value) -> GosValue {
>     match value.clone() {
>         ....
>         Value::Object(m) => {
>             ctx.new_map(m.into_iter().map(|(k, v)|{
>                 let _val = FfiCtx::new_interface(to_go_value(ctx, v.clone()), None); // <<== I have no idea what to use instead of `None`
>                 (FfiCtx::new_string(&k), _val)
>             }).collect())
>         }
>     }
> }
> ```



> So I am sending data from FFI function to the runtime as an interface, this data could be any underlying type. The test scenario I worked with sends a `map[string]interface{}` which will be received as an `interface{}` type in Goscript code, it gets trickier by the time I try to access the map's elements , that was when I started getting the type assertion errors.
> 
> Based on your comment in the commit above:
> 
> > if you pass `None` to clone_mb_from, the returned interface won't behave like
> > a normal interface. you cannot cast it or call it's methods.
> 
> Consider this code:
> 
> ```go
> package main
> 
> import "my_ffi"
> 
> func main() {
> 	var in = my_ffi.GetData()
> 	// get inputs
> 	data, ok := in.(map[string]interface{})
> 	assert(ok)
> 
> 	left, _ := data["left"].(int) // <<== Type assertion error starts here
> 	right, _ := data["right"].(int)
> }
> ```
> 
> How do I know what to pass into `clone_mb_from` ?
> 
> This is how I convert `serde_json::Value` types to `GosValue`
> 
> ```rust
> fn to_go_value(ctx: &FfiCtx, value: Value) -> GosValue {
>     match value.clone() {
>         ....
>         Value::Object(m) => {
>             ctx.new_map(m.into_iter().map(|(k, v)|{
>                 let _val = FfiCtx::new_interface(to_go_value(ctx, v.clone()), None); // <<== I have no idea what to use instead of `None`
>                 (FfiCtx::new_string(&k), _val)
>             }).collect())
>         }
>     }
> }
> ```

I realized the previous API requires too much understanding of the inner workings, I changed it so that you need to pass the metas of the interface and the value. Which are still hard to use, will figure out some improments.
For now, for your case, you can get the interface meta via PrimitiveMeta.empty_iface, and Meta::new_map() for the value.

**Comment by darmie** [comment]
> it looks like you are trying to convert arbitrary serde_json::Value to an Goscript interface, that's not possible. What you can do is to create a FFI via which your Goscript code can access the json::Value.
What you are trying to do is basically asking Goscript to be a dynamic language, but currently it cannot. I will consider to add a special "Dynamic" type to meet requirements like yours.

I have a function that checks the internal type of the json value, 

```rs
fn map_go_types(v: Value) -> ValueType {
    match v {
        Value::Null => ValueType::Void,
        Value::Bool(_) => ValueType::Bool,
        Value::Number(n) => {
            if n.is_f64() {
                ValueType::Float64
            } else if n.is_i64() {
                ValueType::Int64
            } else {
                ValueType::Uint64
            }
        }
        Value::String(_) => ValueType::String,
        Value::Array(_) => ValueType::Array,
        Value::Object(_) => ValueType::Map,
    }
}
```
For object and array, it does a recursive walk through their element values and check their types. 

For example, an array
```rs
 Value::Array(a) => {
    let data = a
                .iter()
                .map(|d| to_go_value(ctx, d.clone())) // <<== calling to_go_value to convert element values recursively
                .collect::<Vec<_>>();

            ctx.new_array(data, map_go_types(value))  
}
```
This is why I rely on "interface{}" types on the Go side of things, to afford the flexibility of casting the value to the necessary type on demand.  This is currently possible with the Go runtime. 
This should work successfully in Goscript if I send an interface{} from an FFI function

https://go.dev/play/p/gCIT99MbBNz

**Comment by darmie** [comment]
> For now, for your case, you can get the interface meta via PrimitiveMeta.empty_iface, and Meta::new_map() for the value. For examples, see
https://github.com/oxfeeefeee/goscript/blob/master/std/os/file.gos
https://github.com/oxfeeefeee/goscript/blob/master/engine/src/std/os.rs

Closely watching these files, I have now created an UnsafePtr and FFI module specifically for accessing dynamic data. 

Looking forward to an official `Dynamic` API though :)

**Comment by oxfeeefeee** [comment]
> https://go.dev/play/p/gCIT99MbBNz

This should work in Goscript as well.
It's different from creating interfaces from FFI, as the compiler gets all the type info and store it in the interface.
But it does't work for now because it triggers another unrelated codegen bug :), working on it.

**Comment by darmie** [comment]
I am excited to see Goscript fully working, it's currently an experimental embedded runtime for my project [zflow](https://github.com/zflow-dev/zflow). 

so this is how I am currently handling the data, based on your suggestion:
```rs
#[derive(Ffi)]
pub struct ZflowDataFfi;

#[ffi_impl(rename = "zflow.data")]
impl ZflowDataFfi {
    pub fn ffi_is_nil(ptr:GosValue) -> RuntimeResult<GosValue> {
        let data = ptr.as_non_nil_unsafe_ptr()?.downcast_ref::<ZflowData>()?;
        return Ok(GosValue::from(data.get_nil().is_some()))
    }
    pub fn ffi_i64(ptr:GosValue) -> RuntimeResult<(GosValue, GosValue)> {
        let data = ptr.as_non_nil_unsafe_ptr()?.downcast_ref::<ZflowData>()?;
     
        if let Some(data)= data.get_i64() {
            return Ok((GosValue::from(data), true.into()))
        }
        Ok((FfiCtx::new_nil(ValueType::Int64), false.into()))
    }
    pub fn ffi_u64(ptr:GosValue) -> RuntimeResult<(GosValue, GosValue)> {
        let data = ptr.as_non_nil_unsafe_ptr()?.downcast_ref::<ZflowData>()?;
     
        if let Some(data)= data.get_u64() {
            return Ok((GosValue::from(data), true.into()))
        }
        Ok((FfiCtx::new_nil(ValueType::Uint64), false.into()))
    }
    pub fn ffi_f64(ptr:GosValue) -> RuntimeResult<(GosValue, GosValue)> {
        let data = ptr.as_non_nil_unsafe_ptr()?.downcast_ref::<ZflowData>()?;
     
        if let Some(data)= data.get_f64() {
            return Ok((GosValue::from(data), true.into()))
        }
        Ok((FfiCtx::new_nil(ValueType::Float64), false.into()))
    }
    pub fn ffi_object(ctx:&mut FfiCtx, ptr:GosValue) -> RuntimeResult<(GosValue, GosValue)> {
        let data = ptr.as_non_nil_unsafe_ptr()?.downcast_ref::<ZflowData>()?;
        if let Some(data)= data.get_object() {
            return Ok((ctx.new_map(data), true.into()))
        }
        Ok((FfiCtx::new_nil(ValueType::Map), false.into()))
    }
    pub fn ffi_array(ctx:&mut FfiCtx, ptr:GosValue) -> RuntimeResult<(GosValue, GosValue)> {
        let data = ptr.as_non_nil_unsafe_ptr()?.downcast_ref::<ZflowData>()?;
        if let Some(data)= data.get_arr() {
            return Ok((ctx.new_array(data, ValueType::UnsafePtr), true.into()))
        }
        Ok((FfiCtx::new_nil(ValueType::Array), false.into()))
    }
}




#[derive(UnsafePtr)]
pub struct ZflowData {
    internal: Value
}

impl ZflowData {
    pub (crate) fn from_data(value:Value) -> Self {
        Self{
            internal: value
        }
    }
    pub (crate) fn get_nil(&self)-> Option<()> {
        self.internal.as_null()
    }
    pub (crate) fn get_i64(&self)-> Option<i64> {
        self.internal.as_i64()
    }
    pub (crate) fn get_f64(&self)-> Option<f64> {
        self.internal.as_f64()
    }
    pub (crate) fn get_u64(&self)-> Option<u64> {
        self.internal.as_u64()
    }
    pub (crate) fn get_object(&self) -> Option<HashMap<GosValue, GosValue>> {
        let m = self.internal.as_object()?;
        Some(m.into_iter().map(|(k, v)| (GosValue::from(k.clone()), Self::from_data(v.clone()).into_val())).collect())
    }
    pub (crate) fn get_arr(&self) -> Option<Vec<GosValue>> {
        let m = self.internal.as_array()?;
        Some(m.into_iter().map(|v| Self::from_data(v.clone()).into_val()).collect())
    }

    pub (crate) fn into_val(self) -> GosValue {
        FfiCtx::new_unsafe_ptr(Rc::new(self))
    }

}

```

**Comment by oxfeeefeee** [comment]
> I am excited to see Goscript fully working, it's currently an experimental embedded runtime for my project [zflow](https://github.com/zflow-dev/zflow).

Glad to hear! Your feedback has been very helpful.
