### ISSUE TITLE
Infinite loop with certain input

### ISSUE THREAD

**Issue by MakotoE** [oxfeeefeee/goscript#3]
[This section of the code](https://github.com/oxfeeefeee/goscript/blob/7f41846cff84d3b8f1255b16e8ac9617de4b6a8b/parser/src/scanner.rs#L340) loops infinitely with input <code>`</code>.

```rust
#[test]
fn test() {
    let mut fs = fe::FileSet::new();
    let o = &mut fe::objects::Objects::new();
    let el = &mut fe::errors::ErrorList::new();
    parse_file(o, &mut fs, el, "/a", "`", false);
}
```

**Comment by oxfeeefeee** [comment]
fixed

**Comment by oxfeeefeee** [comment]
and thanks for the first issue!
